# ~/.config/foot/foot.ini
# Mirrors linux/nixos/configuration.nix programs.foot settings.
include=~/.config/foot/themes/catppuccin-macchiato

[main]
font=JetBrainsMono Nerd Font:size=11, monospace=size=11

[colors-dark]
alpha=0.80
