## ---- Aliases ---- ##
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias c=clear
alias cat='/opt/homebrew/bin/bat'
alias dkm='lazydocker'
alias dms='podman machine start -q'
alias dmx='podman machine stop'
alias docker='podman'
alias docker-compose='podman-compose'
alias gac='git add -A && git commit -m'
alias gb='git branch'
alias gbd='git branch -D'
alias gco='git checkout'
alias gd='git diff -w'
alias gds='git diff -w --staged'
alias gg='lazygit'
alias gla=pretty_git_log_all
alias grep='/opt/homebrew/bin/rg'
alias gst='git rev-parse --git-dir > /dev/null 2>&1 && git status || eza'
alias hf='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias h='my_history'
alias hs='my_history | grep'
alias hsi='my_history | grep -i'
alias l='eza --oneline'
alias ll='eza -lh --icons --no-permissions --no-filesize --no-user --group-directories-first --colour=always'
alias ls='eza -ah --icons --no-permissions --group-directories-first --colour=always'
alias lsa='eza -lah --icons --group-directories-first --colour=always'
alias nv='/opt/homebrew/bin/nvim'
alias pf='btop'
alias rm=trash
alias sf='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias sys='fastfetch'
alias tf='terraform'
alias vim='/opt/homebrew/bin/nvim'
