## ---- Aliases ---- ##
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias c=clear
alias cat='/opt/homebrew/bin/bat'
alias docker='podman'
alias e='/opt/homebrew/bin/nvim'
alias gac='git add -A && git commit -m'
alias gb='git branch'
alias gbd='git branch -D'
alias gco='git checkout'
alias gd='git diff -w'
alias gds='git diff -w --staged'
alias grs='git restore --staged'
alias gshs='git stash'
alias gshl='git stash list'
alias gsha='git stash apply'
alias gshp='git stash pop'
alias gshd='git stash drop'
alias gst='git rev-parse --git-dir > /dev/null 2>&1 && git status || eza'
alias grd='git fetch origin && git rebase origin/master'
alias gla=pretty_git_log_all
alias grep='/opt/homebrew/bin/rg'
alias hf='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias h='my_history'
alias hs='my_history | grep'
alias hsi='my_history | grep -i'
alias l='eza --oneline'
alias ll='eza -lh --icons --no-permissions --no-filesize --no-user --group-directories-first --colour=always'
alias ls='eza -ah --icons --no-permissions --group-directories-first --colour=always'
alias lsa='eza -lah --icons --group-directories-first --colour=always'
alias lzd='lazydocker'
alias lzg='lazygit'
alias nv='/opt/homebrew/bin/nvim'
alias pf='btop'
alias rm=trash
alias sf='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias stat='fastfetch'
alias vim='/opt/homebrew/bin/nvim'
