set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"   # use homebrew path
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g status-interval 1    # make status bar more responsive
setw -g automatic-rename off


set -g mouse on
set -g status-position top  # place status bar at top rather than bottom
set -g base-index 1         # start indexing windows at 1 instead of 0
set -g pane-base-index 1    # start indexing panes at 1 instead of 0
set -g set-clipboard on     # use system clipboard
set -g renumber-windows on  # renumber all windows when any window is closed
set-option -g focus-events on

unbind C-b

set-option -g prefix C-a

bind C-a send-prefix

unbind %
bind \\ split-window -h
unbind '"'
bind - split-window -v
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux configuration reloaded!"

# Use vim keymaps to navigate panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# prefix and vim keymaps to resize panes
bind -r h resize-pane -L
bind -r j resize-pane -D
bind -r k resize-pane -U
bind -r l resize-pane -R

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# Launch Opencode in a Popup in current directory
bind -n C-o popup -E -d "#{pane_current_path}" -w 55% -h 75% "EDITOR=nvim /opt/homebrew/bin/opencode"

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'omerxx/tmux-sessionx'

# theme
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_status_background 'none'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_number_color "#{@thm_blue}"
set -g @catppuccin_window_current_text " #W"

# status bar
set -g status-left-length 25
set -g status-right-length 125
set -g status-left "#[bg=default,fg=#{@thm_peach}] #[bg=#{@thm_peach},fg=#{@thm_surface_0}]#S#[bg=default,fg=#{@thm_peach}] "
set -g status-right "#[fg=#f9e2af]  #(~/.config/tmux/path_mapper.sh \"#{pane_current_path}\") #[bg=default,fg=#{@thm_green}]#[bg=#{@thm_green},fg=#{@thm_surface_0}]#{pane_index}:#{pane_current_command}#[bg=default,fg=#{@thm_green}]"

# session manager
set -g @sessionx-bind 'o'
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-window-height '30%'
set -g @sessionx-window-width '25%'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager
run '/opt/homebrew/opt/tpm/share/tpm/tpm'
