set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"   # use homebrew path
# set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"   # use homebrew path
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g status-interval 1    # make status bar more responsive
setw -g automatic-rename off

set -g mouse on
set -g status-position top  # place status bar at top rather than bottom
set -g base-index 1         # start indexing windows at 1 instead of 0
set -g pane-base-index 1    # start indexing panes at 1 instead of 0
set -g set-clipboard on     # use system clipboard
set -g renumber-windows on  # renumber all windows when any window is closed
set-option -g focus-events on

unbind C-b

set-option -g prefix C-a

bind C-a send-prefix

# Pane and new window options
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Reload configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux configuration reloaded!"

# Use vim keymaps to navigate panes
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# prefix and vim keymaps to resize panes
bind -r h resize-pane -L
bind -r j resize-pane -D
bind -r k resize-pane -U
bind -r l resize-pane -R

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

# Style
gray_light="#D8DEE9"
gray_medium="#ABB2BF"
gray_dark="#3B4252"
green_soft="#A3BE8C"
blue_muted="#81A1C1"
cyan_soft="#88C0D0"

# status bar
set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=#{gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold]   #S #[fg=${gray_light},nobold] | "
set -g status-right " #{cpu}  #{mem}   #(~/.config/tmux/path_mapper.sh \"#{pane_current_path}\"  )"
set -g window-status-current-format "#[fg=${cyan_soft},bold][#I]"
set -g window-status-format " #I "
set -g message-style "fg=${gray_light},bg=default"
set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${gray_medium}"

# session manager
set -g @sessionx-bind 'o'
set -g @sessionx-preview-enabled 'false'
set -g @sessionx-window-height '30%'
set -g @sessionx-window-width '25%'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager
run '/tpm/share/tpm/tpm'
# run '/opt/homebrew/opt/tpm/share/tpm/tpm'
